const activities = [
  {
    activity: "Go for a hike",
    type: "recreational",
    participants: 2,
    price: 0,
    link: "https://example.com/hike",
    key: "hike123",
  },
  {
    activity: "Attend a cooking class",
    type: "education",
    participants: 1,
    price: 30,
    link: "https://example.com/cooking-class",
    key: "cook456",
  },
  {
    activity: "Visit a museum",
    type: "recreational",
    participants: 1,
    price: 15,
    link: "https://example.com/museum",
    key: "museum789",
  },
  {
    activity: "Play board games",
    type: "social",
    participants: 4,
    price: 10,
    link: "https://example.com/board-games",
    key: "board101",
  },
  {
    activity: "Take a yoga class",
    type: "health",
    participants: 1,
    price: 20,
    link: "https://example.com/yoga-class",
    key: "yoga102",
  },
  {
    activity: "Join a book club",
    type: "social",
    participants: 8,
    price: 0,
    link: "https://example.com/book-club",
    key: "book103",
  },
  {
    activity: "Watch a movie",
    type: "entertainment",
    participants: 3,
    price: 12,
    link: "https://example.com/movie",
    key: "movie104",
  },
  {
    activity: "Go kayaking",
    type: "recreational",
    participants: 2,
    price: 25,
    link: "https://example.com/kayaking",
    key: "kayak105",
  },
  {
    activity: "Attend a concert",
    type: "entertainment",
    participants: 2,
    price: 50,
    link: "https://example.com/concert",
    key: "concert106",
  },
  {
    activity: "Visit a botanical garden",
    type: "recreational",
    participants: 2,
    price: 10,
    link: "https://example.com/botanical-garden",
    key: "garden107",
  },
  {
    activity: "Go to a theater play",
    type: "entertainment",
    participants: 1,
    price: 40,
    link: "https://example.com/theater-play",
    key: "theater108",
  },
  {
    activity: "Paint a picture",
    type: "creative",
    participants: 1,
    price: 5,
    link: "https://example.com/paint",
    key: "paint109",
  },
  {
    activity: "Do a puzzle",
    type: "recreational",
    participants: 1,
    price: 0,
    link: "https://example.com/puzzle",
    key: "puzzle110",
  },
  {
    activity: "Go on a picnic",
    type: "recreational",
    participants: 2,
    price: 10,
    link: "https://example.com/picnic",
    key: "picnic111",
  },
  {
    activity: "Take a dance class",
    type: "health",
    participants: 1,
    price: 25,
    link: "https://example.com/dance-class",
    key: "dance112",
  },
  {
    activity: "Learn a new language",
    type: "education",
    participants: 1,
    price: 0,
    link: "https://example.com/learn-language",
    key: "language113",
  },
  {
    activity: "Play tennis",
    type: "sports",
    participants: 2,
    price: 10,
    link: "https://example.com/tennis",
    key: "tennis114",
  },
  {
    activity: "Go swimming",
    type: "recreational",
    participants: 1,
    price: 5,
    link: "https://example.com/swimming",
    key: "swim115",
  },
  {
    activity: "Read a book",
    type: "recreational",
    participants: 1,
    price: 0,
    link: "https://example.com/read-book",
    key: "book116",
  },
  {
    activity: "Write a short story",
    type: "creative",
    participants: 1,
    price: 0,
    link: "https://example.com/write-story",
    key: "story117",
  },
  {
    activity: "Go bird watching",
    type: "recreational",
    participants: 1,
    price: 0,
    link: "https://example.com/bird-watching",
    key: "bird118",
  },
  {
    activity: "Try a new recipe",
    type: "creative",
    participants: 1,
    price: 0,
    link: "https://example.com/new-recipe",
    key: "recipe119",
  },
  {
    activity: "Visit a local farm",
    type: "recreational",
    participants: 2,
    price: 5,
    link: "https://example.com/local-farm",
    key: "farm120",
  },
  {
    activity: "Have a spa day",
    type: "relaxation",
    participants: 1,
    price: 50,
    link: "https://example.com/spa-day",
    key: "spa121",
  },
  {
    activity: "Go ice skating",
    type: "recreational",
    participants: 2,
    price: 15,
    link: "https://example.com/ice-skating",
    key: "skate122",
  },
  {
    activity: "Go to a comedy show",
    type: "entertainment",
    participants: 2,
    price: 20,
    link: "https://example.com/comedy-show",
    key: "comedy123",
  },
  {
    activity: "Play mini golf",
    type: "recreational",
    participants: 4,
    price: 10,
    link: "https://example.com/mini-golf",
    key: "golf124",
  },
  {
    activity: "Go stargazing",
    type: "recreational",
    participants: 1,
    price: 0,
    link: "https://example.com/stargazing",
    key: "stars125",
  },
  {
    activity: "Take a pottery class",
    type: "creative",
    participants: 1,
    price: 35,
    link: "https://example.com/pottery-class",
    key: "pottery126",
  },
  {
    activity: "Go on a road trip",
    type: "recreational",
    participants: 2,
    price: 50,
    link: "https://example.com/road-trip",
    key: "road127",
  },
  {
    activity: "Do some gardening",
    type: "recreational",
    participants: 1,
    price: 0,
    link: "https://example.com/gardening",
    key: "garden128",
  },
  {
    activity: "Go fishing",
    type: "recreational",
    participants: 2,
    price: 10,
    link: "https://example.com/fishing",
    key: "fish129",
  },
  {
    activity: "Visit an aquarium",
    type: "recreational",
    participants: 2,
    price: 20,
    link: "https://example.com/aquarium",
    key: "aquarium130",
  },
  {
    activity: "Do a workout",
    type: "health",
    participants: 1,
    price: 0,
    link: "https://example.com/workout",
    key: "workout131",
  },
  {
    activity: "Go rollerblading",
    type: "recreational",
    participants: 1,
    price: 0,
    link: "https://example.com/rollerblading",
    key: "blade132",
  },
  {
    activity: "Try a new restaurant",
    type: "social",
    participants: 2,
    price: 50,
    link: "https://example.com/new-restaurant",
    key: "restaurant133",
  },
  {
    activity: "Visit a theme park",
    type: "recreational",
    participants: 3,
    price: 60,
    link: "https://example.com/theme-park",
    key: "park134",
  },
  {
    activity: "Go zip lining",
    type: "recreational",
    participants: 2,
    price: 40,
    link: "https://example.com/zip-lining",
    key: "zip135",
  },
  {
    activity: "Do some volunteer work",
    type: "social",
    participants: 1,
    price: 0,
    link: "https://example.com/volunteer",
    key: "volunteer136",
  },
  {
    activity: "Go to a fair",
    type: "recreational",
    participants: 2,
    price: 20,
    link: "https://example.com/fair",
    key: "fair137",
  },
  {
    activity: "Try a new sport",
    type: "sports",
    participants: 2,
    price: 0,
    link: "https://example.com/new-sport",
    key: "sport138",
  },
  {
    activity: "Go to a zoo",
    type: "recreational",
    participants: 2,
    price: 20,
    link: "https://example.com/zoo",
    key: "zoo139",
  },
  {
    activity: "Have a beach day",
    type: "recreational",
    participants: 2,
    price: 0,
    link: "https://example.com/beach",
    key: "beach140",
  },
  {
    activity: "Attend a workshop",
    type: "education",
    participants: 1,
    price: 30,
    link: "https://example.com/workshop",
    key: "workshop141",
  },
  {
    activity: "Go horseback riding",
    type: "recreational",
    participants: 1,
    price: 50,
    link: "https://example.com/horseback-riding",
    key: "horse142",
  },
  {
    activity: "Take a photography class",
    type: "creative",
    participants: 1,
    price: 30,
    link: "https://example.com/photography-class",
    key: "photo143",
  },
  {
    activity: "Go on a boat ride",
    type: "recreational",
    participants: 2,
    price: 30,
    link: "https://example.com/boat-ride",
    key: "boat144",
  },
  {
    activity: "Do a meditation session",
    type: "relaxation",
    participants: 1,
    price: 0,
    link: "https://example.com/meditation",
    key: "meditation145",
  },
  {
    activity: "Go rock climbing",
    type: "recreational",
    participants: 1,
    price: 25,
    link: "https://example.com/rock-climbing",
    key: "climb146",
  },
  {
    activity: "Attend a sports event",
    type: "entertainment",
    participants: 2,
    price: 50,
    link: "https://example.com/sports-event",
    key: "sportsevent147",
  },
  {
    activity: "Go snorkeling",
    type: "recreational",
    participants: 2,
    price: 40,
    link: "https://example.com/snorkeling",
    key: "snorkel148",
  },
  {
    activity: "Go camping",
    type: "recreational",
    participants: 4,
    price: 30,
    link: "https://example.com/camping",
    key: "camp149",
  },
  {
    activity: "Visit a historical site",
    type: "recreational",
    participants: 2,
    price: 20,
    link: "https://example.com/historical-site",
    key: "history150",
  },
  {
    activity: "Try indoor skydiving",
    type: "recreational",
    participants: 1,
    price: 60,
    link: "https://example.com/indoor-skydiving",
    key: "skydiving151",
  },
  {
    activity: "Join a fitness class",
    type: "health",
    participants: 1,
    price: 15,
    link: "https://example.com/fitness-class",
    key: "fitness152",
  },
  {
    activity: "Go to a trampoline park",
    type: "recreational",
    participants: 2,
    price: 20,
    link: "https://example.com/trampoline-park",
    key: "trampoline153",
  },
  {
    activity: "Go skiing",
    type: "recreational",
    participants: 2,
    price: 50,
    link: "https://example.com/skiing",
    key: "ski154",
  },
  {
    activity: "Take a coding class",
    type: "education",
    participants: 1,
    price: 20,
    link: "https://example.com/coding-class",
    key: "coding155",
  },
  {
    activity: "Visit a planetarium",
    type: "recreational",
    participants: 2,
    price: 10,
    link: "https://example.com/planetarium",
    key: "planetarium156",
  },
  {
    activity: "Go to a farmers market",
    type: "recreational",
    participants: 1,
    price: 0,
    link: "https://example.com/farmers-market",
    key: "market157",
  },
  {
    activity: "Take a painting class",
    type: "creative",
    participants: 1,
    price: 25,
    link: "https://example.com/painting-class",
    key: "painting158",
  },
  {
    activity: "Visit a science center",
    type: "recreational",
    participants: 2,
    price: 15,
    link: "https://example.com/science-center",
    key: "science159",
  },
  {
    activity: "Take a wine tasting tour",
    type: "social",
    participants: 2,
    price: 30,
    link: "https://example.com/wine-tasting",
    key: "wine160",
  },
  {
    activity: "Go on a safari",
    type: "recreational",
    participants: 2,
    price: 80,
    link: "https://example.com/safari",
    key: "safari161",
  },
  {
    activity: "Visit a castle",
    type: "recreational",
    participants: 2,
    price: 20,
    link: "https://example.com/castle",
    key: "castle162",
  },
  {
    activity: "Try archery",
    type: "recreational",
    participants: 1,
    price: 15,
    link: "https://example.com/archery",
    key: "archery163",
  },
  {
    activity: "Take a baking class",
    type: "education",
    participants: 1,
    price: 30,
    link: "https://example.com/baking-class",
    key: "baking164",
  },
  {
    activity: "Go to a haunted house",
    type: "entertainment",
    participants: 2,
    price: 20,
    link: "https://example.com/haunted-house",
    key: "haunted165",
  },
  {
    activity: "Take a cooking class",
    type: "education",
    participants: 1,
    price: 30,
    link: "https://example.com/cooking-class",
    key: "cook166",
  },
  {
    activity: "Go hiking",
    type: "recreational",
    participants: 2,
    price: 0,
    link: "https://example.com/hiking",
    key: "hike167",
  },
  {
    activity: "Visit a hot spring",
    type: "recreational",
    participants: 2,
    price: 20,
    link: "https://example.com/hot-spring",
    key: "hotspring168",
  },
  {
    activity: "Go to a drive-in theater",
    type: "entertainment",
    participants: 2,
    price: 15,
    link: "https://example.com/drive-in-theater",
    key: "drivein169",
  },
  {
    activity: "Do an escape room",
    type: "recreational",
    participants: 4,
    price: 25,
    link: "https://example.com/escape-room",
    key: "escape170",
  },
  {
    activity: "Go on a ghost tour",
    type: "recreational",
    participants: 2,
    price: 15,
    link: "https://example.com/ghost-tour",
    key: "ghost171",
  },
  {
    activity: "Go paragliding",
    type: "recreational",
    participants: 1,
    price: 70,
    link: "https://example.com/paragliding",
    key: "paraglide172",
  },
  {
    activity: "Do a hot air balloon ride",
    type: "recreational",
    participants: 2,
    price: 100,
    link: "https://example.com/hot-air-balloon",
    key: "balloon173",
  },
  {
    activity: "Go to a magic show",
    type: "entertainment",
    participants: 2,
    price: 25,
    link: "https://example.com/magic-show",
    key: "magic174",
  },
  {
    activity: "Visit a lighthouse",
    type: "recreational",
    participants: 2,
    price: 10,
    link: "https://example.com/lighthouse",
    key: "lighthouse175",
  },
  {
    activity: "Go scuba diving",
    type: "recreational",
    participants: 2,
    price: 70,
    link: "https://example.com/scuba-diving",
    key: "scuba176",
  },
  {
    activity: "Go on a segway tour",
    type: "recreational",
    participants: 2,
    price: 40,
    link: "https://example.com/segway-tour",
    key: "segway177",
  },
  {
    activity: "Go surfing",
    type: "recreational",
    participants: 1,
    price: 30,
    link: "https://example.com/surfing",
    key: "surf178",
  },
  {
    activity: "Go to a water park",
    type: "recreational",
    participants: 3,
    price: 50,
    link: "https://example.com/water-park",
    key: "water179",
  },
  {
    activity: "Visit a wildlife sanctuary",
    type: "recreational",
    participants: 2,
    price: 20,
    link: "https://example.com/wildlife-sanctuary",
    key: "wildlife180",
  },
  {
    activity: "Go ziplining",
    type: "recreational",
    participants: 2,
    price: 40,
    link: "https://example.com/ziplining",
    key: "zipline181",
  },
  {
    activity: "Go to a flea market",
    type: "recreational",
    participants: 2,
    price: 0,
    link: "https://example.com/flea-market",
    key: "flea182",
  },
  {
    activity: "Try geocaching",
    type: "recreational",
    participants: 2,
    price: 0,
    link: "https://example.com/geocaching",
    key: "geo183",
  },
  {
    activity: "Go mountain biking",
    type: "recreational",
    participants: 2,
    price: 30,
    link: "https://example.com/mountain-biking",
    key: "bike184",
  },
  {
    activity: "Visit a brewery",
    type: "recreational",
    participants: 2,
    price: 20,
    link: "https://example.com/brewery",
    key: "brew185",
  },
  {
    activity: "Go whale watching",
    type: "recreational",
    participants: 2,
    price: 50,
    link: "https://example.com/whale-watching",
    key: "whale186",
  },
  {
    activity: "Visit a car show",
    type: "recreational",
    participants: 1,
    price: 10,
    link: "https://example.com/car-show",
    key: "car187",
  },
  {
    activity: "Try glass blowing",
    type: "creative",
    participants: 1,
    price: 60,
    link: "https://example.com/glass-blowing",
    key: "glass188",
  },
  {
    activity: "Take a ceramics class",
    type: "creative",
    participants: 1,
    price: 35,
    link: "https://example.com/ceramics-class",
    key: "ceramics189",
  },
  {
    activity: "Go sandboarding",
    type: "recreational",
    participants: 1,
    price: 20,
    link: "https://example.com/sandboarding",
    key: "sandboard190",
  },
  {
    activity: "Do some knitting",
    type: "creative",
    participants: 1,
    price: 0,
    link: "https://example.com/knitting",
    key: "knit191",
  },
  {
    activity: "Go on a scenic train ride",
    type: "recreational",
    participants: 2,
    price: 30,
    link: "https://example.com/scenic-train-ride",
    key: "train192",
  },
  {
    activity: "Go to an amusement park",
    type: "recreational",
    participants: 4,
    price: 60,
    link: "https://example.com/amusement-park",
    key: "amusement193",
  },
  {
    activity: "Go to a jazz club",
    type: "entertainment",
    participants: 2,
    price: 20,
    link: "https://example.com/jazz-club",
    key: "jazz194",
  },
  {
    activity: "Take a helicopter tour",
    type: "recreational",
    participants: 2,
    price: 150,
    link: "https://example.com/helicopter-tour",
    key: "helicopter195",
  },
  {
    activity: "Visit a butterfly garden",
    type: "recreational",
    participants: 2,
    price: 10,
    link: "https://example.com/butterfly-garden",
    key: "butterfly196",
  },
  {
    activity: "Go to a classical music concert",
    type: "entertainment",
    participants: 2,
    price: 40,
    link: "https://example.com/classical-music",
    key: "classical197",
  },
  {
    activity: "Visit a national park",
    type: "recreational",
    participants: 2,
    price: 20,
    link: "https://example.com/national-park",
    key: "national198",
  },
  {
    activity: "Try indoor rock climbing",
    type: "recreational",
    participants: 2,
    price: 25,
    link: "https://example.com/indoor-climbing",
    key: "indoor199",
  },
  {
    activity: "Go to a farmers market",
    type: "recreational",
    participants: 1,
    price: 0,
    link: "https://example.com/farmers-market",
    key: "market200",
  },
];

function getRandomIndex(n: number) {
  return Math.floor(Math.random() * (n + 1));
}

export async function GET(request: Request) {
  const randomIndex = getRandomIndex(activities.length - 1);

  return Response.json({
    success: true,
    data: activities[randomIndex],
  });
}
